### ISSUE TITLE
During simple install, failing...

### ISSUE THREAD

**Issue by danielheth** [ariemtech/pisignage-server#4]
Following install instructions exactly and came across an error during the npm install piece...  this is from the npm_debug.log

4008 error Failed to parse json
4008 error Unexpected token t
4009 error File: /home/daniel/.npm/range-parser/1.0.2/package/package.json
4010 error Failed to parse package.json data.
4010 error package.json must be actual JSON, not just JavaScript.
4010 error
4010 error This is not a bug in npm.
4010 error Tell the package author to fix their package.json file. JSON.parse
4011 error System Linux 3.13.0-24-generic
4012 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
4013 error cwd /home/daniel/pisignage-server
4014 error node -v v0.10.25
4015 error npm -v 1.3.10
4016 error file /home/daniel/.npm/range-parser/1.0.2/package/package.json
4017 error code EJSONPARSE
4018 verbose exit [ 1, true ]

**Comment by ariemtech** [comment]
It is a package.json parse error. Can you try with the unmodified package.json  file from repository?

I think there are some quotes missing in the json file when it was modified for config and media servers.

**Comment by ariemtech** [comment]
Few steps to make sure things are OK
- first run mongod and make sure it is listening at default port without errors (27017)
- run node server.js and see that it is listening at port 3000 without errors
- Are you able to see the full pisignage.com like UI when you do "http://localhost:3000"
- Are you able to ping server IP from Pi
- Make sure in your server machine, node port (default 3000) is enabled for access (firewall configuration)
- in Pi package.json, entries have to like "config_server”:”192.168.55.55:3000”, “media_server”:”192.168.55.55:3000", where 192.168.55.55 is the server IP address and 3000 is the port.
- In your server under directory /data/releases/package.json file update the release to 1.1.5 and the upgrade button won’t be shown.
